source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 3.2.2'

gem 'rails', '~> 7.1.0'
gem 'sqlite3', '~> 2.8'
gem 'puma', '~> 6.0'
gem 'importmap-rails'
gem 'sprockets-rails'
gem 'turbo-rails'
gem 'stimulus-rails'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'ruby-openai'
gem 'dotenv-rails', groups: [:development, :test]
gem 'httparty'
gem 'redcarpet'
gem 'rouge'
gem 'tzinfo-data'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'web-console', '>= 4.1.0'
  gem 'listen', '~> 3.3'
  gem 'spring'
end

